// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: puffin.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_puffin_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_puffin_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_puffin_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_puffin_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace puffin {
namespace metadata {
class BitExtent;
class BitExtentDefaultTypeInternal;
extern BitExtentDefaultTypeInternal _BitExtent_default_instance_;
class PatchHeader;
class PatchHeaderDefaultTypeInternal;
extern PatchHeaderDefaultTypeInternal _PatchHeader_default_instance_;
class StreamInfo;
class StreamInfoDefaultTypeInternal;
extern StreamInfoDefaultTypeInternal _StreamInfo_default_instance_;
}  // namespace metadata
}  // namespace puffin
PROTOBUF_NAMESPACE_OPEN
template<> ::puffin::metadata::BitExtent* Arena::CreateMaybeMessage<::puffin::metadata::BitExtent>(Arena*);
template<> ::puffin::metadata::PatchHeader* Arena::CreateMaybeMessage<::puffin::metadata::PatchHeader>(Arena*);
template<> ::puffin::metadata::StreamInfo* Arena::CreateMaybeMessage<::puffin::metadata::StreamInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace puffin {
namespace metadata {

enum PatchHeader_PatchType : int {
  PatchHeader_PatchType_BSDIFF = 0,
  PatchHeader_PatchType_ZUCCHINI = 1,
  PatchHeader_PatchType_PatchHeader_PatchType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PatchHeader_PatchType_PatchHeader_PatchType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PatchHeader_PatchType_IsValid(int value);
constexpr PatchHeader_PatchType PatchHeader_PatchType_PatchType_MIN = PatchHeader_PatchType_BSDIFF;
constexpr PatchHeader_PatchType PatchHeader_PatchType_PatchType_MAX = PatchHeader_PatchType_ZUCCHINI;
constexpr int PatchHeader_PatchType_PatchType_ARRAYSIZE = PatchHeader_PatchType_PatchType_MAX + 1;

const std::string& PatchHeader_PatchType_Name(PatchHeader_PatchType value);
template<typename T>
inline const std::string& PatchHeader_PatchType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PatchHeader_PatchType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PatchHeader_PatchType_Name.");
  return PatchHeader_PatchType_Name(static_cast<PatchHeader_PatchType>(enum_t_value));
}
bool PatchHeader_PatchType_Parse(
    const std::string& name, PatchHeader_PatchType* value);
// ===================================================================

class BitExtent PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:puffin.metadata.BitExtent) */ {
 public:
  inline BitExtent() : BitExtent(nullptr) {};
  virtual ~BitExtent();

  BitExtent(const BitExtent& from);
  BitExtent(BitExtent&& from) noexcept
    : BitExtent() {
    *this = ::std::move(from);
  }

  inline BitExtent& operator=(const BitExtent& from) {
    CopyFrom(from);
    return *this;
  }
  inline BitExtent& operator=(BitExtent&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const BitExtent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BitExtent* internal_default_instance() {
    return reinterpret_cast<const BitExtent*>(
               &_BitExtent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BitExtent& a, BitExtent& b) {
    a.Swap(&b);
  }
  inline void Swap(BitExtent* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BitExtent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BitExtent* New() const final {
    return CreateMaybeMessage<BitExtent>(nullptr);
  }

  BitExtent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BitExtent>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const BitExtent& from);
  void MergeFrom(const BitExtent& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BitExtent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "puffin.metadata.BitExtent";
  }
  protected:
  explicit BitExtent(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOffsetFieldNumber = 1,
    kLengthFieldNumber = 2,
  };
  // uint64 offset = 1;
  void clear_offset();
  ::PROTOBUF_NAMESPACE_ID::uint64 offset() const;
  void set_offset(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_offset() const;
  void _internal_set_offset(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 length = 2;
  void clear_length();
  ::PROTOBUF_NAMESPACE_ID::uint64 length() const;
  void set_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_length() const;
  void _internal_set_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:puffin.metadata.BitExtent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 offset_;
  ::PROTOBUF_NAMESPACE_ID::uint64 length_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_puffin_2eproto;
};
// -------------------------------------------------------------------

class StreamInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:puffin.metadata.StreamInfo) */ {
 public:
  inline StreamInfo() : StreamInfo(nullptr) {};
  virtual ~StreamInfo();

  StreamInfo(const StreamInfo& from);
  StreamInfo(StreamInfo&& from) noexcept
    : StreamInfo() {
    *this = ::std::move(from);
  }

  inline StreamInfo& operator=(const StreamInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamInfo& operator=(StreamInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const StreamInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StreamInfo* internal_default_instance() {
    return reinterpret_cast<const StreamInfo*>(
               &_StreamInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(StreamInfo& a, StreamInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StreamInfo* New() const final {
    return CreateMaybeMessage<StreamInfo>(nullptr);
  }

  StreamInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StreamInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const StreamInfo& from);
  void MergeFrom(const StreamInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StreamInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "puffin.metadata.StreamInfo";
  }
  protected:
  explicit StreamInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeflatesFieldNumber = 1,
    kPuffsFieldNumber = 2,
    kPuffLengthFieldNumber = 3,
  };
  // repeated .puffin.metadata.BitExtent deflates = 1;
  int deflates_size() const;
  private:
  int _internal_deflates_size() const;
  public:
  void clear_deflates();
  ::puffin::metadata::BitExtent* mutable_deflates(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::puffin::metadata::BitExtent >*
      mutable_deflates();
  private:
  const ::puffin::metadata::BitExtent& _internal_deflates(int index) const;
  ::puffin::metadata::BitExtent* _internal_add_deflates();
  public:
  const ::puffin::metadata::BitExtent& deflates(int index) const;
  ::puffin::metadata::BitExtent* add_deflates();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::puffin::metadata::BitExtent >&
      deflates() const;

  // repeated .puffin.metadata.BitExtent puffs = 2;
  int puffs_size() const;
  private:
  int _internal_puffs_size() const;
  public:
  void clear_puffs();
  ::puffin::metadata::BitExtent* mutable_puffs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::puffin::metadata::BitExtent >*
      mutable_puffs();
  private:
  const ::puffin::metadata::BitExtent& _internal_puffs(int index) const;
  ::puffin::metadata::BitExtent* _internal_add_puffs();
  public:
  const ::puffin::metadata::BitExtent& puffs(int index) const;
  ::puffin::metadata::BitExtent* add_puffs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::puffin::metadata::BitExtent >&
      puffs() const;

  // uint64 puff_length = 3;
  void clear_puff_length();
  ::PROTOBUF_NAMESPACE_ID::uint64 puff_length() const;
  void set_puff_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_puff_length() const;
  void _internal_set_puff_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:puffin.metadata.StreamInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::puffin::metadata::BitExtent > deflates_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::puffin::metadata::BitExtent > puffs_;
  ::PROTOBUF_NAMESPACE_ID::uint64 puff_length_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_puffin_2eproto;
};
// -------------------------------------------------------------------

class PatchHeader PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:puffin.metadata.PatchHeader) */ {
 public:
  inline PatchHeader() : PatchHeader(nullptr) {};
  virtual ~PatchHeader();

  PatchHeader(const PatchHeader& from);
  PatchHeader(PatchHeader&& from) noexcept
    : PatchHeader() {
    *this = ::std::move(from);
  }

  inline PatchHeader& operator=(const PatchHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline PatchHeader& operator=(PatchHeader&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const PatchHeader& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PatchHeader* internal_default_instance() {
    return reinterpret_cast<const PatchHeader*>(
               &_PatchHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PatchHeader& a, PatchHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(PatchHeader* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PatchHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PatchHeader* New() const final {
    return CreateMaybeMessage<PatchHeader>(nullptr);
  }

  PatchHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PatchHeader>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const PatchHeader& from);
  void MergeFrom(const PatchHeader& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PatchHeader* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "puffin.metadata.PatchHeader";
  }
  protected:
  explicit PatchHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef PatchHeader_PatchType PatchType;
  static constexpr PatchType BSDIFF =
    PatchHeader_PatchType_BSDIFF;
  static constexpr PatchType ZUCCHINI =
    PatchHeader_PatchType_ZUCCHINI;
  static inline bool PatchType_IsValid(int value) {
    return PatchHeader_PatchType_IsValid(value);
  }
  static constexpr PatchType PatchType_MIN =
    PatchHeader_PatchType_PatchType_MIN;
  static constexpr PatchType PatchType_MAX =
    PatchHeader_PatchType_PatchType_MAX;
  static constexpr int PatchType_ARRAYSIZE =
    PatchHeader_PatchType_PatchType_ARRAYSIZE;
  template<typename T>
  static inline const std::string& PatchType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, PatchType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function PatchType_Name.");
    return PatchHeader_PatchType_Name(enum_t_value);
  }
  static inline bool PatchType_Parse(const std::string& name,
      PatchType* value) {
    return PatchHeader_PatchType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSrcFieldNumber = 2,
    kDstFieldNumber = 3,
    kVersionFieldNumber = 1,
    kTypeFieldNumber = 4,
  };
  // .puffin.metadata.StreamInfo src = 2;
  bool has_src() const;
  private:
  bool _internal_has_src() const;
  public:
  void clear_src();
  const ::puffin::metadata::StreamInfo& src() const;
  ::puffin::metadata::StreamInfo* release_src();
  ::puffin::metadata::StreamInfo* mutable_src();
  void set_allocated_src(::puffin::metadata::StreamInfo* src);
  private:
  const ::puffin::metadata::StreamInfo& _internal_src() const;
  ::puffin::metadata::StreamInfo* _internal_mutable_src();
  public:
  void unsafe_arena_set_allocated_src(
      ::puffin::metadata::StreamInfo* src);
  ::puffin::metadata::StreamInfo* unsafe_arena_release_src();

  // .puffin.metadata.StreamInfo dst = 3;
  bool has_dst() const;
  private:
  bool _internal_has_dst() const;
  public:
  void clear_dst();
  const ::puffin::metadata::StreamInfo& dst() const;
  ::puffin::metadata::StreamInfo* release_dst();
  ::puffin::metadata::StreamInfo* mutable_dst();
  void set_allocated_dst(::puffin::metadata::StreamInfo* dst);
  private:
  const ::puffin::metadata::StreamInfo& _internal_dst() const;
  ::puffin::metadata::StreamInfo* _internal_mutable_dst();
  public:
  void unsafe_arena_set_allocated_dst(
      ::puffin::metadata::StreamInfo* dst);
  ::puffin::metadata::StreamInfo* unsafe_arena_release_dst();

  // int32 version = 1;
  void clear_version();
  ::PROTOBUF_NAMESPACE_ID::int32 version() const;
  void set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_version() const;
  void _internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .puffin.metadata.PatchHeader.PatchType type = 4;
  void clear_type();
  ::puffin::metadata::PatchHeader_PatchType type() const;
  void set_type(::puffin::metadata::PatchHeader_PatchType value);
  private:
  ::puffin::metadata::PatchHeader_PatchType _internal_type() const;
  void _internal_set_type(::puffin::metadata::PatchHeader_PatchType value);
  public:

  // @@protoc_insertion_point(class_scope:puffin.metadata.PatchHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::puffin::metadata::StreamInfo* src_;
  ::puffin::metadata::StreamInfo* dst_;
  ::PROTOBUF_NAMESPACE_ID::int32 version_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_puffin_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BitExtent

// uint64 offset = 1;
inline void BitExtent::clear_offset() {
  offset_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 BitExtent::_internal_offset() const {
  return offset_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 BitExtent::offset() const {
  // @@protoc_insertion_point(field_get:puffin.metadata.BitExtent.offset)
  return _internal_offset();
}
inline void BitExtent::_internal_set_offset(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  offset_ = value;
}
inline void BitExtent::set_offset(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:puffin.metadata.BitExtent.offset)
}

// uint64 length = 2;
inline void BitExtent::clear_length() {
  length_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 BitExtent::_internal_length() const {
  return length_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 BitExtent::length() const {
  // @@protoc_insertion_point(field_get:puffin.metadata.BitExtent.length)
  return _internal_length();
}
inline void BitExtent::_internal_set_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  length_ = value;
}
inline void BitExtent::set_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:puffin.metadata.BitExtent.length)
}

// -------------------------------------------------------------------

// StreamInfo

// repeated .puffin.metadata.BitExtent deflates = 1;
inline int StreamInfo::_internal_deflates_size() const {
  return deflates_.size();
}
inline int StreamInfo::deflates_size() const {
  return _internal_deflates_size();
}
inline void StreamInfo::clear_deflates() {
  deflates_.Clear();
}
inline ::puffin::metadata::BitExtent* StreamInfo::mutable_deflates(int index) {
  // @@protoc_insertion_point(field_mutable:puffin.metadata.StreamInfo.deflates)
  return deflates_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::puffin::metadata::BitExtent >*
StreamInfo::mutable_deflates() {
  // @@protoc_insertion_point(field_mutable_list:puffin.metadata.StreamInfo.deflates)
  return &deflates_;
}
inline const ::puffin::metadata::BitExtent& StreamInfo::_internal_deflates(int index) const {
  return deflates_.Get(index);
}
inline const ::puffin::metadata::BitExtent& StreamInfo::deflates(int index) const {
  // @@protoc_insertion_point(field_get:puffin.metadata.StreamInfo.deflates)
  return _internal_deflates(index);
}
inline ::puffin::metadata::BitExtent* StreamInfo::_internal_add_deflates() {
  return deflates_.Add();
}
inline ::puffin::metadata::BitExtent* StreamInfo::add_deflates() {
  // @@protoc_insertion_point(field_add:puffin.metadata.StreamInfo.deflates)
  return _internal_add_deflates();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::puffin::metadata::BitExtent >&
StreamInfo::deflates() const {
  // @@protoc_insertion_point(field_list:puffin.metadata.StreamInfo.deflates)
  return deflates_;
}

// repeated .puffin.metadata.BitExtent puffs = 2;
inline int StreamInfo::_internal_puffs_size() const {
  return puffs_.size();
}
inline int StreamInfo::puffs_size() const {
  return _internal_puffs_size();
}
inline void StreamInfo::clear_puffs() {
  puffs_.Clear();
}
inline ::puffin::metadata::BitExtent* StreamInfo::mutable_puffs(int index) {
  // @@protoc_insertion_point(field_mutable:puffin.metadata.StreamInfo.puffs)
  return puffs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::puffin::metadata::BitExtent >*
StreamInfo::mutable_puffs() {
  // @@protoc_insertion_point(field_mutable_list:puffin.metadata.StreamInfo.puffs)
  return &puffs_;
}
inline const ::puffin::metadata::BitExtent& StreamInfo::_internal_puffs(int index) const {
  return puffs_.Get(index);
}
inline const ::puffin::metadata::BitExtent& StreamInfo::puffs(int index) const {
  // @@protoc_insertion_point(field_get:puffin.metadata.StreamInfo.puffs)
  return _internal_puffs(index);
}
inline ::puffin::metadata::BitExtent* StreamInfo::_internal_add_puffs() {
  return puffs_.Add();
}
inline ::puffin::metadata::BitExtent* StreamInfo::add_puffs() {
  // @@protoc_insertion_point(field_add:puffin.metadata.StreamInfo.puffs)
  return _internal_add_puffs();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::puffin::metadata::BitExtent >&
StreamInfo::puffs() const {
  // @@protoc_insertion_point(field_list:puffin.metadata.StreamInfo.puffs)
  return puffs_;
}

// uint64 puff_length = 3;
inline void StreamInfo::clear_puff_length() {
  puff_length_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StreamInfo::_internal_puff_length() const {
  return puff_length_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StreamInfo::puff_length() const {
  // @@protoc_insertion_point(field_get:puffin.metadata.StreamInfo.puff_length)
  return _internal_puff_length();
}
inline void StreamInfo::_internal_set_puff_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  puff_length_ = value;
}
inline void StreamInfo::set_puff_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_puff_length(value);
  // @@protoc_insertion_point(field_set:puffin.metadata.StreamInfo.puff_length)
}

// -------------------------------------------------------------------

// PatchHeader

// int32 version = 1;
inline void PatchHeader::clear_version() {
  version_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PatchHeader::_internal_version() const {
  return version_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PatchHeader::version() const {
  // @@protoc_insertion_point(field_get:puffin.metadata.PatchHeader.version)
  return _internal_version();
}
inline void PatchHeader::_internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  version_ = value;
}
inline void PatchHeader::set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:puffin.metadata.PatchHeader.version)
}

// .puffin.metadata.StreamInfo src = 2;
inline bool PatchHeader::_internal_has_src() const {
  return this != internal_default_instance() && src_ != nullptr;
}
inline bool PatchHeader::has_src() const {
  return _internal_has_src();
}
inline void PatchHeader::clear_src() {
  if (GetArena() == nullptr && src_ != nullptr) {
    delete src_;
  }
  src_ = nullptr;
}
inline const ::puffin::metadata::StreamInfo& PatchHeader::_internal_src() const {
  const ::puffin::metadata::StreamInfo* p = src_;
  return p != nullptr ? *p : *reinterpret_cast<const ::puffin::metadata::StreamInfo*>(
      &::puffin::metadata::_StreamInfo_default_instance_);
}
inline const ::puffin::metadata::StreamInfo& PatchHeader::src() const {
  // @@protoc_insertion_point(field_get:puffin.metadata.PatchHeader.src)
  return _internal_src();
}
inline void PatchHeader::unsafe_arena_set_allocated_src(
    ::puffin::metadata::StreamInfo* src) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(src_);
  }
  src_ = src;
  if (src) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:puffin.metadata.PatchHeader.src)
}
inline ::puffin::metadata::StreamInfo* PatchHeader::release_src() {
  auto temp = unsafe_arena_release_src();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::puffin::metadata::StreamInfo* PatchHeader::unsafe_arena_release_src() {
  // @@protoc_insertion_point(field_release:puffin.metadata.PatchHeader.src)
  
  ::puffin::metadata::StreamInfo* temp = src_;
  src_ = nullptr;
  return temp;
}
inline ::puffin::metadata::StreamInfo* PatchHeader::_internal_mutable_src() {
  
  if (src_ == nullptr) {
    auto* p = CreateMaybeMessage<::puffin::metadata::StreamInfo>(GetArena());
    src_ = p;
  }
  return src_;
}
inline ::puffin::metadata::StreamInfo* PatchHeader::mutable_src() {
  // @@protoc_insertion_point(field_mutable:puffin.metadata.PatchHeader.src)
  return _internal_mutable_src();
}
inline void PatchHeader::set_allocated_src(::puffin::metadata::StreamInfo* src) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete src_;
  }
  if (src) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(src);
    if (message_arena != submessage_arena) {
      src = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, src, submessage_arena);
    }
    
  } else {
    
  }
  src_ = src;
  // @@protoc_insertion_point(field_set_allocated:puffin.metadata.PatchHeader.src)
}

// .puffin.metadata.StreamInfo dst = 3;
inline bool PatchHeader::_internal_has_dst() const {
  return this != internal_default_instance() && dst_ != nullptr;
}
inline bool PatchHeader::has_dst() const {
  return _internal_has_dst();
}
inline void PatchHeader::clear_dst() {
  if (GetArena() == nullptr && dst_ != nullptr) {
    delete dst_;
  }
  dst_ = nullptr;
}
inline const ::puffin::metadata::StreamInfo& PatchHeader::_internal_dst() const {
  const ::puffin::metadata::StreamInfo* p = dst_;
  return p != nullptr ? *p : *reinterpret_cast<const ::puffin::metadata::StreamInfo*>(
      &::puffin::metadata::_StreamInfo_default_instance_);
}
inline const ::puffin::metadata::StreamInfo& PatchHeader::dst() const {
  // @@protoc_insertion_point(field_get:puffin.metadata.PatchHeader.dst)
  return _internal_dst();
}
inline void PatchHeader::unsafe_arena_set_allocated_dst(
    ::puffin::metadata::StreamInfo* dst) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(dst_);
  }
  dst_ = dst;
  if (dst) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:puffin.metadata.PatchHeader.dst)
}
inline ::puffin::metadata::StreamInfo* PatchHeader::release_dst() {
  auto temp = unsafe_arena_release_dst();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::puffin::metadata::StreamInfo* PatchHeader::unsafe_arena_release_dst() {
  // @@protoc_insertion_point(field_release:puffin.metadata.PatchHeader.dst)
  
  ::puffin::metadata::StreamInfo* temp = dst_;
  dst_ = nullptr;
  return temp;
}
inline ::puffin::metadata::StreamInfo* PatchHeader::_internal_mutable_dst() {
  
  if (dst_ == nullptr) {
    auto* p = CreateMaybeMessage<::puffin::metadata::StreamInfo>(GetArena());
    dst_ = p;
  }
  return dst_;
}
inline ::puffin::metadata::StreamInfo* PatchHeader::mutable_dst() {
  // @@protoc_insertion_point(field_mutable:puffin.metadata.PatchHeader.dst)
  return _internal_mutable_dst();
}
inline void PatchHeader::set_allocated_dst(::puffin::metadata::StreamInfo* dst) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete dst_;
  }
  if (dst) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(dst);
    if (message_arena != submessage_arena) {
      dst = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, dst, submessage_arena);
    }
    
  } else {
    
  }
  dst_ = dst;
  // @@protoc_insertion_point(field_set_allocated:puffin.metadata.PatchHeader.dst)
}

// .puffin.metadata.PatchHeader.PatchType type = 4;
inline void PatchHeader::clear_type() {
  type_ = 0;
}
inline ::puffin::metadata::PatchHeader_PatchType PatchHeader::_internal_type() const {
  return static_cast< ::puffin::metadata::PatchHeader_PatchType >(type_);
}
inline ::puffin::metadata::PatchHeader_PatchType PatchHeader::type() const {
  // @@protoc_insertion_point(field_get:puffin.metadata.PatchHeader.type)
  return _internal_type();
}
inline void PatchHeader::_internal_set_type(::puffin::metadata::PatchHeader_PatchType value) {
  
  type_ = value;
}
inline void PatchHeader::set_type(::puffin::metadata::PatchHeader_PatchType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:puffin.metadata.PatchHeader.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace metadata
}  // namespace puffin

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::puffin::metadata::PatchHeader_PatchType> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_puffin_2eproto
